import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Flat config, matching ../www. The upstream client this was ported from still
// carries the legacy FlatCompat shim, which throws on ESLint 9 — it never
// surfaced there because its lint script called `next lint`, removed in
// Next 16, so linting simply did not run.
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Inherited from the upstream client, not introduced here. Both rules are
    // new in eslint-config-next 16 (React Compiler era) and fire on the
    // load-then-setState effect this app uses on nearly every page — working
    // code, not bugs, and the build and type check are clean.
    //
    // Warn, not off: they still print, so they are visible rather than hidden.
    // They are errors-worth-fixing, but the fix belongs in
    // Coastal-Carolina-Tech/webmail, where rmyllc, CCT and FCH would all get
    // it. Rewriting 13 effects only in this fork would buy nothing and make
    // every future diff against upstream harder to read.
    //
    // New violations in code written here should be fixed, not accumulated.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
    },
  },
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Cloudflare build output — generated by `opennextjs-cloudflare build`.
    ".open-next/**",
    ".wrangler/**",
    "cloudflare-env.d.ts",
  ]),
]);

export default eslintConfig;
